create table public.clinicas (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  nombre text null,
  logo text null,
  slug text null,
  constraint clinicas_pkey primary key (id),
  constraint clinicas_slug_key unique (slug)
) TABLESPACE pg_default;

create table public.usuarios_clinica (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  user_id uuid not null,
  clinica_id bigint not null,
  role text not null default 'staff',
  constraint usuarios_clinica_pkey primary key (id),
  constraint usuarios_clinica_user_clinica_unique unique (user_id, clinica_id),
  constraint usuarios_clinica_role_check check (role in ('admin', 'staff')),
  constraint usuarios_clinica_clinica_id_fkey foreign KEY (clinica_id) references clinicas (id),
  constraint usuarios_clinica_user_id_fkey foreign KEY (user_id) references auth.users (id)
) TABLESPACE pg_default;

create table public.pacientes (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  clinica_id bigint not null,
  foto_perfil_url text null,
  nombre text not null,
  apellido text not null,
  dni text null,
  email text null,
  obra_social text null,
  plan_obra_social text null,
  especialidad text[] null,
  numero_interno text null,
  sexo text null,
  fecha_nacimiento date not null,
  ciudad text null,
  direccion text null,
  telefono_principal text null,
  telefono_alternativo text null,
  observaciones text null,
  constraint pacientes_pkey primary key (id),
  constraint pacientes_clinica_dni_unique unique (clinica_id, dni),
  constraint pacientes_clinica_id_fkey foreign KEY (clinica_id) references clinicas (id),
  constraint pacientes_sexo_check check (sexo in ('masculino', 'femenino', 'otro')),
  constraint pacientes_especialidad_check check (
    especialidad is null
    or (
      especialidad <@ array['ortopedia', 'ortodoncia']::text[]
      and cardinality(especialidad) between 1 and 2
    )
  )
) TABLESPACE pg_default;

create table public.obras_sociales (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  nombre text not null,
  logo text null,
  constraint obras_sociales_pkey primary key (id),
  constraint obras_sociales_nombre_key unique (nombre)
) TABLESPACE pg_default;

create table public.pacientes_obras_sociales (
  paciente_id bigint not null,
  obra_social_id bigint not null,
  created_at timestamp with time zone not null default now(),
  constraint pacientes_obras_sociales_pkey primary key (paciente_id, obra_social_id),
  constraint pacientes_obras_sociales_paciente_id_fkey
    foreign key (paciente_id) references public.pacientes (id) on delete cascade,
  constraint pacientes_obras_sociales_obra_social_id_fkey
    foreign key (obra_social_id) references public.obras_sociales (id)
) TABLESPACE pg_default;

insert into public.obras_sociales (nombre, logo)
values
  ('IOSCOR', null),
  ('PAMI', null),
  ('OSECAC', null),
  ('UPCN', null),
  ('UOCRA', null),
  ('OSPRERA', null),
  ('Unión Personal', null),
  ('OSDEPYM', null),
  ('OSUTHGRA', null),
  ('SMATA', null),
  ('IOSFA', null),
  ('Obra Social Policía Federal', null),
  ('Obra Social Servicio Penitenciario', null),
  ('OSDE', null),
  ('Swiss Medical', null),
  ('Medifé', null),
  ('Galeno', null),
  ('Sancor Salud', null),
  ('OSPE', null),
  ('OSPATCA', null),
  ('OSPT', null),
  ('OSPOCE', null),
  ('OSJERA', null),
  ('Jerárquicos Salud', null)
on conflict do nothing;

create extension if not exists pg_trgm;

create index if not exists pacientes_clinica_id_idx
  on public.pacientes using btree (clinica_id);

create unique index if not exists obras_sociales_nombre_lower_idx
  on public.obras_sociales using btree (lower(nombre));

create index if not exists pacientes_obras_sociales_paciente_id_idx
  on public.pacientes_obras_sociales using btree (paciente_id);

create index if not exists pacientes_obras_sociales_obra_social_id_idx
  on public.pacientes_obras_sociales using btree (obra_social_id);

create index if not exists pacientes_nombre_trgm_idx
  on public.pacientes using gin (lower(nombre) gin_trgm_ops);

create index if not exists pacientes_apellido_trgm_idx
  on public.pacientes using gin (lower(apellido) gin_trgm_ops);

create index if not exists pacientes_dni_trgm_idx
  on public.pacientes using gin (lower(dni) gin_trgm_ops);

insert into
  storage.buckets (id, name, public)
values
  ('patient-avatars', 'patient-avatars', true)
on conflict (id) do nothing;
