create table public.clinicas (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  nombre text null,
  logo text null,
  slug text null,
  constraint clinicas_pkey primary key (id),
  constraint clinicas_slug_key unique (slug)
) TABLESPACE pg_default;

create table public.usuarios_clinica (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  user_id uuid not null,
  clinica_id bigint not null,
  role text not null default 'staff',
  constraint usuarios_clinica_pkey primary key (id),
  constraint usuarios_clinica_user_clinica_unique unique (user_id, clinica_id),
  constraint usuarios_clinica_role_check check (role in ('admin', 'staff')),
  constraint usuarios_clinica_clinica_id_fkey foreign KEY (clinica_id) references clinicas (id),
  constraint usuarios_clinica_user_id_fkey foreign KEY (user_id) references auth.users (id)
) TABLESPACE pg_default;

create table public.pacientes (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  clinica_id bigint not null,
  foto_perfil_url text null,
  nombre text not null,
  apellido text not null,
  dni text null,
  email text null,
  obra_social text null,
  plan_obra_social text null,
  especialidad text null,
  numero_interno text null,
  sexo text null,
  fecha_nacimiento date not null,
  ciudad text null,
  direccion text null,
  telefono_principal text null,
  telefono_alternativo text null,
  observaciones text null,
  constraint pacientes_pkey primary key (id),
  constraint pacientes_clinica_dni_unique unique (clinica_id, dni),
  constraint pacientes_clinica_id_fkey foreign KEY (clinica_id) references clinicas (id),
  constraint pacientes_sexo_check check (sexo in ('masculino', 'femenino', 'otro')),
  constraint pacientes_especialidad_check check (especialidad in ('ortopedia', 'ortodoncia'))
) TABLESPACE pg_default;

insert into
  storage.buckets (id, name, public)
values
  ('patient-avatars', 'patient-avatars', true)
on conflict (id) do nothing;
