-- Catálogo de obras sociales y prepagas frecuentes en Corrientes.
-- Agrega relación muchos-a-muchos entre pacientes y obras sociales.

create table if not exists public.obras_sociales (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  nombre text not null,
  logo text null,
  constraint obras_sociales_pkey primary key (id),
  constraint obras_sociales_nombre_key unique (nombre)
) TABLESPACE pg_default;

create unique index if not exists obras_sociales_nombre_lower_idx
  on public.obras_sociales using btree (lower(nombre));

insert into public.obras_sociales (nombre, logo)
values
  ('IOSCOR', null),
  ('PAMI', null),
  ('OSECAC', null),
  ('UPCN', null),
  ('UOCRA', null),
  ('OSPRERA', null),
  ('Unión Personal', null),
  ('OSDEPYM', null),
  ('OSUTHGRA', null),
  ('SMATA', null),
  ('IOSFA', null),
  ('Obra Social Policía Federal', null),
  ('Obra Social Servicio Penitenciario', null),
  ('OSDE', null),
  ('Swiss Medical', null),
  ('Medifé', null),
  ('Galeno', null),
  ('Sancor Salud', null),
  ('OSPE', null),
  ('OSPATCA', null),
  ('OSPTV', null),
  ('OSPOCE', null),
  ('OSJERA', null),
  ('Jerárquicos Salud', null)
on conflict do nothing;

create table if not exists public.pacientes_obras_sociales (
  paciente_id bigint not null,
  obra_social_id bigint not null,
  created_at timestamp with time zone not null default now(),
  constraint pacientes_obras_sociales_pkey primary key (paciente_id, obra_social_id),
  constraint pacientes_obras_sociales_paciente_id_fkey
    foreign key (paciente_id) references public.pacientes (id) on delete cascade,
  constraint pacientes_obras_sociales_obra_social_id_fkey
    foreign key (obra_social_id) references public.obras_sociales (id)
) TABLESPACE pg_default;

create index if not exists pacientes_obras_sociales_paciente_id_idx
  on public.pacientes_obras_sociales using btree (paciente_id);

create index if not exists pacientes_obras_sociales_obra_social_id_idx
  on public.pacientes_obras_sociales using btree (obra_social_id);

with patient_insurances as (
  select
    p.id as paciente_id,
    case
      when p.obra_social is null or btrim(p.obra_social) = '' then null
      when lower(btrim(p.obra_social)) like 'osde%' then 'OSDE'
      when lower(btrim(p.obra_social)) like 'ioscor%' then 'IOSCOR'
      when lower(btrim(p.obra_social)) like 'pami%' then 'PAMI'
      when lower(btrim(p.obra_social)) like 'osecac%' then 'OSECAC'
      when lower(btrim(p.obra_social)) like 'upcn%' then 'UPCN'
      when lower(btrim(p.obra_social)) like 'uocra%' then 'UOCRA'
      when lower(btrim(p.obra_social)) like 'osprera%' then 'OSPRERA'
      when lower(btrim(p.obra_social)) like 'union personal%' then 'Unión Personal'
      when lower(btrim(p.obra_social)) like 'unión personal%' then 'Unión Personal'
      when lower(btrim(p.obra_social)) like 'osdepym%' then 'OSDEPYM'
      when lower(btrim(p.obra_social)) like 'osuthgra%' then 'OSUTHGRA'
      when lower(btrim(p.obra_social)) like 'smata%' then 'SMATA'
      when lower(btrim(p.obra_social)) like 'iosfa%' then 'IOSFA'
      when lower(btrim(p.obra_social)) like 'medife%' then 'Medifé'
      when lower(btrim(p.obra_social)) like 'medifé%' then 'Medifé'
      when lower(btrim(p.obra_social)) like 'galeno%' then 'Galeno'
      when lower(btrim(p.obra_social)) like 'sancor%' then 'Sancor Salud'
      when lower(btrim(p.obra_social)) like 'ospe%' then 'OSPE'
      when lower(btrim(p.obra_social)) like 'ospatca%' then 'OSPATCA'
      when lower(btrim(p.obra_social)) like 'ospt%' then 'OSPT'
      when lower(btrim(p.obra_social)) like 'ospoce%' then 'OSPOCE'
      when lower(btrim(p.obra_social)) like 'osjera%' then 'OSJERA'
      when lower(btrim(p.obra_social)) like 'jerarquicos salud%' then 'Jerárquicos Salud'
      when lower(btrim(p.obra_social)) like 'jerárquicos salud%' then 'Jerárquicos Salud'
      when lower(btrim(p.obra_social)) like 'obra social policia federal%' then 'Obra Social Policía Federal'
      when lower(btrim(p.obra_social)) like 'obra social policía federal%' then 'Obra Social Policía Federal'
      when lower(btrim(p.obra_social)) like 'obra social servicio penitenciario%' then 'Obra Social Servicio Penitenciario'
      else p.obra_social
    end as obra_social_nombre
  from public.pacientes p
)
insert into public.pacientes_obras_sociales (paciente_id, obra_social_id)
select
  pi.paciente_id,
  os.id
from patient_insurances pi
join public.obras_sociales os
  on lower(os.nombre) = lower(btrim(pi.obra_social_nombre))
where pi.obra_social_nombre is not null
on conflict do nothing;
